In [33]:
import numpy as np

X = [[0, 0], 
     [0, 1], 
     [1, 0], 
     [1, 1]]

X_train = np.array(X) 
y = [0, 0, 0, 1]    # target (y) for AND gate
# y = [0, 1, 1, 1]  # OR Gate
# y = [0, 1, 1, 0]  # XOR
y_train = np.array(y)

In [34]:
from sklearn.linear_model import Perceptron
model = Perceptron(random_state=0, verbose=True)
model.fit(X_train,y_train)

-- Epoch 1
Norm: 0.00, NNZs: 0, Bias: -1.000000, T: 4, Avg. loss: 0.750000
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 1.41, NNZs: 2, Bias: 0.000000, T: 8, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.00, NNZs: 0, Bias: -2.000000, T: 12, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 1.41, NNZs: 2, Bias: -1.000000, T: 16, Avg. loss: 0.500000
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 1.00, NNZs: 1, Bias: -2.000000, T: 20, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 2.24, NNZs: 2, Bias: -1.000000, T: 24, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 1.00, NNZs: 1, Bias: -3.000000, T: 28, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 2.24, NNZs: 2, Bias: -2.000000, T: 32, Avg. loss: 0.500000
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 1.41, NNZs: 2, Bias: -3.000000, T: 36, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- E

Perceptron(verbose=True)

In [35]:
print('score:', model.score(X_train, y_train)) 
print('predicted:', model.predict(X_train))
print('target:   ', np.array(y))

score: 1.0
predicted: [0 0 0 1]
target:    [0 0 0 1]


In [36]:
print('weight [w1 w2] =',model.coef_[0]) 
print('w0 (bias) =',model.intercept_[0])

weight [w1 w2] = [2. 2.]
w0 (bias) = -2.0


In [37]:
X_train

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [38]:
X_new = X_train
model.predict(X_new)

array([0, 0, 0, 1])

In [39]:
X_new = [[0,1]]
a = model.predict(X_new)
a[0]

0

In [40]:
X_new = [[1,1]]
b = model.predict(X_new)
b[0]

1

In [41]:
X_new = [[0, 1],
         [1, 1]]
c = model.predict(X_new)
c

array([0, 1])

In [42]:
# ไม่ใช่ library
# scratch code
def and_gate(x1, x2):
    w0 = -2  # bias
    w1 = 2
    w2 = 2
  
    threshold = 0.0 
    
    s = w0 + (w1 * x1) + (w2 * x2) 

    if s > threshold:  #
        result = 1
    else:
        result = 0
        
    print('output y={}   [s={:.2f}]' . format(result, s))

and_gate(0, 0)
and_gate(0, 1)
and_gate(1, 0)
and_gate(1, 1)

output y=0   [s=-2.00]
output y=0   [s=0.00]
output y=0   [s=0.00]
output y=1   [s=2.00]
